trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build
        steps: 
         - task: Docker@2
           inputs:
             containerRegistry: 'serviceconncs5'
             repository: 'cs5registrycs'
             command: 'buildAndPush'
             Dockerfile: '**/Dockerfile'

         - task: HelmInstaller@0
           inputs:
             helmVersion: '2.14.1'
             installKubectl: true    

         - task: HelmDeploy@0
           inputs:
             azureSubscriptionForACR: 'AZResourceconn'
             azureResourceGroupForACR: 'rg5cs'
             azureContainerRegistry: 'cs5registrycs'
             command: 'package'
             chartPath: 'emojivoto/emojivoto'     

         - task: PublishBuildArtifacts@1
           inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'  

  - stage: 
    jobs:
      - job: Deploy
        steps: 
         - task: DownloadBuildArtifacts@1
           inputs:
             buildType: 'current'
             downloadType: 'single'
             artifactName: 'drop'
             downloadPath: '$(System.ArtifactsDirectory)'          

         - task: HelmInstaller@0
           inputs:
             helmVersion: '2.14.1'
             installKubectl: true

         - task: HelmDeploy@0
           inputs:
             connectionType: 'Azure Resource Manager'
             azureSubscription: 'Free Trial (426b8104-3a89-42f0-a3f5-14b554b1b2bb)'
             azureResourceGroup: 'devopscs5'
             kubernetesCluster: 'aksclustercs5'
             namespace: 'emojivoto'
             command: 'upgrade'
             chartType: 'FilePath'
             chartPath: 'emojivoto/emoji'
             releaseName: 'emojiapp'
             overrideValues: 'image.tag=$(Build.BuildId)'
